sonar.organization=minxc9
sonar.projectKey=minxc9_JITNONGNOOONG_Mobile-App
sonar.sources=lib
sonar.tests=test
sonar.exclusions=**/build/**,**/.dart_tool/**,**/android/**,**/ios/**,**/linux/**,**/macos/**,**/windows/**,**/web/**
sonar.dart.lcov.reportPaths=coverage/lcov.info
